DATABASE_URL = "postgresql+psycopg2://postgres.hkqhzmimcebrijuvbqfo:rqCCQquvV%237LhTW@aws-1-ap-northeast-1.pooler.supabase.com:6543/postgres?sslmode=require"

SMTP_HOST = "smtp.gmail.com"
SMTP_PORT = "587"
SMTP_USER = "maruchikurieitazu@gmail.com"
SMTP_PASS = "fdjq xspp cqst flac"
SMTP_FROM = "Komazawa Games <maruchikurieitazu@gmail.com>"